<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog comments recaptcha js
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<script>
    require([
        "jquery",
        "domReady!"
    ], function($){
        var rid = '#recaptcha-append-to';
        $('.comment-form-blog-recaptcha, .reply-form-blog-recaptcha').click(function() {
            if (!$(this).find(rid).length) {
                $(rid).appendTo($(this));
            }
        });
    });
</script>
